[package]
name = "pass_by_catastrophe"
version = "0.1.0"
edition = "2021"
description = "Please do not use this."
license = "MIT"

[features]
stable = []

[dependencies.magic-import]
version = "0.2.1"
features = [ "stable" ]